name: Deploy to GitHub Marketplace

on:
  push:
    tags:
      - "v*"

jobs:
  deploy:
    name: Publish GitHub Action
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Publish to GitHub Marketplace
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          npm install -g @actions/cli
          gh action publish . --tag latest